# Generated by Django 6.0.3 on 2026-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
