# Generated by Django 6.0.3 on 2026-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='card', max_length=10),
        ),
    ]
