# Generated by Django 6.0.3 on 2026-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
